// @ts-check
/**
 * Phase 61.4: Local dev environment.
 *
 * One-command dev setup: writes a sensible .env.local, seeds the data/
 * directory with a chosen template (minimal | demo | testing | full), and
 * exposes helpers for verifying the host environment.
 *
 * No external dependencies — everything uses Node's built-in fs/promises,
 * path, crypto, and net modules. JSON files match the shape expected by
 * lib/json-path-store.js and lib/storage.js so the rest of SiskelBot can
 * pick them up as soon as the server boots.
 *
 * @module dev-setup
 */

import fs from "node:fs/promises";
import fsSync from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import net from "node:net";

// ─── Seed templates ─────────────────────────────────────────────────────────

export const SEED_TEMPLATES = {
  minimal: {
    description: "Just enough to start the server",
    users: 0,
    workspaces: 0,
    apiKeys: 0,
    conversations: 0,
    plugins: false,
  },
  demo: {
    description: "Demo workspace with sample data",
    users: 1,
    workspaces: 1,
    apiKeys: 1,
    conversations: 2,
    plugins: false,
  },
  testing: {
    description: "Test users, API keys, preset conversations",
    users: 3,
    workspaces: 2,
    apiKeys: 3,
    conversations: 4,
    plugins: false,
  },
  full: {
    description: "All workspaces, plugins, teams, eval sets",
    users: 4,
    workspaces: 4,
    apiKeys: 4,
    conversations: 6,
    plugins: true,
  },
};

const DEFAULT_PORT = 3000;

// ─── Helpers ────────────────────────────────────────────────────────────────

function sha256(s) {
  return crypto.createHash("sha256").update(String(s)).digest("hex");
}

function randomHex(bytes = 24) {
  return crypto.randomBytes(bytes).toString("hex");
}

function makeId(prefix = "id") {
  return `${prefix}_${Date.now().toString(36)}_${crypto.randomBytes(4).toString("hex")}`;
}

async function exists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

async function writeJson(filePath, data) {
  await ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
}

async function readJsonSafe(filePath, fallback) {
  try {
    const txt = await fs.readFile(filePath, "utf8");
    return JSON.parse(txt);
  } catch {
    return fallback;
  }
}

function storagePathRoot(storagePath) {
  return path.resolve(storagePath || process.env.STORAGE_PATH || "./data");
}

function userScopePath(root, userId, workspaceId) {
  return path.join(root, "users", userId, "workspaces", workspaceId);
}

// ─── Env file generation ───────────────────────────────────────────────────

const ENV_DEFAULTS = [
  { key: "NODE_ENV", value: "development", comment: "Mode" },
  { key: "PORT", value: "3000", comment: "HTTP port" },
  { key: "BACKEND", value: "ollama", comment: "ollama | vllm | openai" },
  { key: "OLLAMA_URL", value: "http://localhost:11434", comment: "Ollama" },
  { key: "VLLM_URL", value: "http://localhost:8000", comment: "vLLM" },
  { key: "STORAGE_BACKEND", value: "json", comment: "json | sqlite | postgres" },
  { key: "STORAGE_PATH", value: "./data", comment: "JSON storage root" },
  { key: "SESSION_SECRET", value: "dev-secret-change-me", comment: "Session cookie secret" },
  { key: "API_KEY", value: "", comment: "Protects /v1/chat/completions (optional in dev)" },
  { key: "ADMIN_API_KEY", value: "", comment: "Protects /admin and /api/admin/*" },
  { key: "OPENAI_API_KEY", value: "", comment: "Set when BACKEND=openai" },
  { key: "ENABLE_METRICS", value: "1", comment: "Expose /metrics" },
];

export async function generateEnvFile(options = {}) {
  const targetPath = options.envPath ? path.resolve(options.envPath) : path.resolve(process.cwd(), ".env.local");
  const force = Boolean(options.force);
  const overrides = options.overrides && typeof options.overrides === "object" ? options.overrides : {};

  if (!force && (await exists(targetPath))) {
    return { path: targetPath, written: false, reason: "exists" };
  }

  const entries = ENV_DEFAULTS.map((entry) => {
    const v = Object.prototype.hasOwnProperty.call(overrides, entry.key) ? overrides[entry.key] : entry.value;
    return { ...entry, value: v };
  });

  // Auto-generate a session secret and admin key if none supplied
  const sessionEntry = entries.find((e) => e.key === "SESSION_SECRET");
  if (sessionEntry && (!sessionEntry.value || sessionEntry.value === "dev-secret-change-me")) {
    sessionEntry.value = "dev_" + randomHex(16);
  }
  const adminEntry = entries.find((e) => e.key === "ADMIN_API_KEY");
  if (adminEntry && !adminEntry.value) {
    adminEntry.value = "dev_admin_" + randomHex(12);
  }

  const header = [
    "# SiskelBot local dev environment",
    "# Generated by lib/dev-setup.js — safe to edit, regenerate with --force.",
    "# DO NOT commit this file; it may contain secrets.",
    "",
  ];
  const body = entries.map((e) => {
    const commentLine = e.comment ? `# ${e.comment}` : "";
    return `${commentLine}\n${e.key}=${e.value ?? ""}`.trim();
  });

  const content = header.concat(body).join("\n") + "\n";
  await ensureDir(path.dirname(targetPath));
  await fs.writeFile(targetPath, content, "utf8");
  return { path: targetPath, written: true };
}

// ─── User / workspace / API key primitives ─────────────────────────────────

export async function createTestUser({ email, role = "user", apiKey, storagePath } = {}) {
  const root = storagePathRoot(storagePath);
  const userId = makeId("user");
  const user = {
    id: userId,
    email: email || `dev-${userId}@example.com`,
    role,
    createdAt: new Date().toISOString(),
    _seed: true,
  };
  const usersPath = path.join(root, "users.json");
  const data = await readJsonSafe(usersPath, { users: [], _version: 1 });
  const arr = Array.isArray(data.users) ? data.users : [];
  // Idempotency: skip if an identical seeded email already exists
  const existing = arr.find((u) => u.email === user.email && u._seed);
  if (existing) return existing;
  arr.push(user);
  await writeJson(usersPath, { users: arr, _version: 1 });

  // Also create the user's personal workspace directory so storage.js list() works
  await ensureDir(userScopePath(root, userId, "default"));

  if (apiKey) {
    await createTestApiKey({ userId, rawKey: apiKey, storagePath: root });
  }
  return user;
}

export async function createTestWorkspace({ name, ownerId, type = "personal", storagePath } = {}) {
  const root = storagePathRoot(storagePath);
  if (!ownerId) throw new Error("ownerId required");
  const workspaceId = makeId("ws");
  const workspace = {
    id: workspaceId,
    name: name || "Dev Workspace",
    ownerId,
    type,
    createdAt: new Date().toISOString(),
    _seed: true,
  };
  const wsDir = path.join(root, "users", ownerId, "workspaces");
  await ensureDir(path.join(wsDir, workspaceId));
  const indexPath = path.join(wsDir, "index.json");
  const data = await readJsonSafe(indexPath, { workspaces: [], _version: 1 });
  const list = Array.isArray(data.workspaces) ? data.workspaces : [];
  const dup = list.find((w) => w.name === workspace.name && w._seed);
  if (dup) return dup;
  list.push(workspace);
  await writeJson(indexPath, { workspaces: list, _version: 1 });
  return workspace;
}

export async function createTestApiKey({ userId, scopes = ["read", "write"], rawKey, storagePath } = {}) {
  const root = storagePathRoot(storagePath);
  if (!userId) throw new Error("userId required");
  const key = rawKey || "sk-dev-" + randomHex(18);
  const entry = {
    id: makeId("key"),
    keyHash: sha256(key),
    masked: key.slice(0, 6) + "…" + key.slice(-4),
    userId,
    scopes: Array.isArray(scopes) && scopes.length ? scopes : ["read", "write"],
    createdAt: new Date().toISOString(),
    _seed: true,
  };
  const filePath = path.join(root, "api-keys.json");
  const data = await readJsonSafe(filePath, { keys: [], _version: 1 });
  const keys = Array.isArray(data.keys) ? data.keys : [];
  keys.push(entry);
  await writeJson(filePath, { keys, _version: 1 });
  return { ...entry, key };
}

// ─── Seeders ────────────────────────────────────────────────────────────────

export async function seedMinimal(storagePath) {
  const root = storagePathRoot(storagePath);
  await ensureDir(root);
  // Ensure the default workspace folder exists so storage reads don't crash.
  await ensureDir(userScopePath(root, "anonymous", "default"));
  // Stamp a marker file so getDevStatus can detect a seed has run.
  const markerPath = path.join(root, ".dev-seed.json");
  await writeJson(markerPath, {
    template: "minimal",
    seededAt: new Date().toISOString(),
    _version: 1,
  });
  return { template: "minimal", root };
}

export async function seedDemo(storagePath) {
  const root = storagePathRoot(storagePath);
  await seedMinimal(root);
  const user = await createTestUser({
    email: "demo@example.com",
    role: "user",
    storagePath: root,
  });
  const workspace = await createTestWorkspace({
    name: "Demo Workspace",
    ownerId: user.id,
    storagePath: root,
  });
  // Seed a couple of sample conversations under the demo workspace
  const convPath = path.join(userScopePath(root, user.id, workspace.id), "conversations.json");
  const conversations = [
    {
      id: makeId("conv"),
      title: "Welcome to SiskelBot",
      messages: [
        { role: "user", content: "Hello!" },
        { role: "assistant", content: "Hi there — this is a demo conversation." },
      ],
      createdAt: new Date().toISOString(),
      _seed: true,
    },
    {
      id: makeId("conv"),
      title: "Sample agent run",
      messages: [
        { role: "user", content: "Plan a trip to Chicago." },
        { role: "assistant", content: "Here's an example plan…" },
      ],
      createdAt: new Date().toISOString(),
      _seed: true,
    },
  ];
  await writeJson(convPath, { items: conversations, _version: 1 });
  await writeJson(path.join(root, ".dev-seed.json"), {
    template: "demo",
    seededAt: new Date().toISOString(),
    users: 1,
    workspaces: 1,
    _version: 1,
  });
  return { template: "demo", root, user, workspace };
}

export async function seedTesting(storagePath) {
  const root = storagePathRoot(storagePath);
  await seedMinimal(root);
  const users = [];
  const keys = [];
  const workspaces = [];
  const roles = ["admin", "user", "viewer"];
  for (let i = 0; i < 3; i++) {
    const user = await createTestUser({
      email: `test-${i + 1}@example.com`,
      role: roles[i],
      storagePath: root,
    });
    users.push(user);
    const ws = await createTestWorkspace({
      name: `Test WS ${i + 1}`,
      ownerId: user.id,
      storagePath: root,
    });
    workspaces.push(ws);
    const key = await createTestApiKey({
      userId: user.id,
      scopes: roles[i] === "admin" ? ["read", "write", "admin"] : ["read", "write"],
      rawKey: `sk-test-${i + 1}-` + randomHex(8),
      storagePath: root,
    });
    keys.push(key);
  }
  // Preset conversations for the admin test user
  const admin = users[0];
  const adminWs = workspaces[0];
  const convPath = path.join(userScopePath(root, admin.id, adminWs.id), "conversations.json");
  const conversations = Array.from({ length: 4 }).map((_, i) => ({
    id: makeId("conv"),
    title: `Preset conversation ${i + 1}`,
    messages: [
      { role: "user", content: `Test message ${i + 1}` },
      { role: "assistant", content: `Test reply ${i + 1}` },
    ],
    createdAt: new Date().toISOString(),
    _seed: true,
  }));
  await writeJson(convPath, { items: conversations, _version: 1 });

  await writeJson(path.join(root, ".dev-seed.json"), {
    template: "testing",
    seededAt: new Date().toISOString(),
    users: users.length,
    workspaces: workspaces.length,
    apiKeys: keys.length,
    _version: 1,
  });
  return { template: "testing", root, users, workspaces, apiKeys: keys };
}

export async function seedFull(storagePath) {
  const root = storagePathRoot(storagePath);
  const testing = await seedTesting(root);

  // Add a fourth "team lead" user with a team workspace
  const lead = await createTestUser({
    email: "lead@example.com",
    role: "user",
    storagePath: root,
  });
  const teamWs = await createTestWorkspace({
    name: "Team Alpha",
    ownerId: lead.id,
    type: "team",
    storagePath: root,
  });
  const leadKey = await createTestApiKey({
    userId: lead.id,
    scopes: ["read", "write", "admin"],
    rawKey: "sk-lead-" + randomHex(8),
    storagePath: root,
  });

  // Team membership record
  const teamsPath = path.join(root, "teams.json");
  const teamsData = await readJsonSafe(teamsPath, { teams: [], _version: 1 });
  const teamsList = Array.isArray(teamsData.teams) ? teamsData.teams : [];
  teamsList.push({
    id: makeId("team"),
    workspaceId: teamWs.id,
    ownerId: lead.id,
    members: [
      { userId: lead.id, role: "owner" },
      ...testing.users.map((u) => ({ userId: u.id, role: "member" })),
    ],
    createdAt: new Date().toISOString(),
    _seed: true,
  });
  await writeJson(teamsPath, { teams: teamsList, _version: 1 });

  // Plugins: installed marketplace manifest stub
  const pluginsPath = path.join(root, "marketplace-installed.json");
  await writeJson(pluginsPath, {
    plugins: [
      {
        id: "dev-hello-plugin",
        name: "Hello Plugin",
        version: "0.1.0",
        enabled: true,
        installedAt: new Date().toISOString(),
        _seed: true,
      },
    ],
    _version: 1,
  });

  // Eval sets seed
  const evalDir = path.join(root, "eval-sets");
  await ensureDir(evalDir);
  await writeJson(path.join(evalDir, "smoke.json"), {
    name: "smoke",
    description: "Minimal dev smoke eval set",
    cases: [
      { id: "hello", input: "Say hi", expected: "hi" },
      { id: "math", input: "What is 2+2?", expected: "4" },
    ],
    _seed: true,
    _version: 1,
  });

  // Sample recipes
  const recipesPath = path.join(userScopePath(root, lead.id, teamWs.id), "recipes.json");
  await writeJson(recipesPath, {
    items: [
      {
        id: makeId("recipe"),
        name: "hello-world",
        description: "Sample recipe",
        steps: [{ tool: "echo", payload: { text: "hello" } }],
        createdAt: new Date().toISOString(),
        _seed: true,
      },
    ],
    _version: 1,
  });

  await writeJson(path.join(root, ".dev-seed.json"), {
    template: "full",
    seededAt: new Date().toISOString(),
    users: testing.users.length + 1,
    workspaces: testing.workspaces.length + 1,
    apiKeys: testing.apiKeys.length + 1,
    teams: 1,
    plugins: 1,
    evalSets: 1,
    _version: 1,
  });

  return {
    template: "full",
    root,
    users: [...testing.users, lead],
    workspaces: [...testing.workspaces, teamWs],
    apiKeys: [...testing.apiKeys, leadKey],
  };
}

// ─── Verification / health ─────────────────────────────────────────────────

export async function checkDependencies() {
  const checks = [];
  // Node version
  const nodeVersion = process.versions.node;
  const major = Number(nodeVersion.split(".")[0] || 0);
  checks.push({
    name: "node_version",
    ok: major >= 18,
    detail: nodeVersion,
    required: ">=18",
  });
  // package.json presence
  const pkgPath = path.resolve(process.cwd(), "package.json");
  checks.push({
    name: "package_json",
    ok: await exists(pkgPath),
    detail: pkgPath,
  });
  // node_modules presence (soft check)
  const nmPath = path.resolve(process.cwd(), "node_modules");
  checks.push({
    name: "node_modules",
    ok: await exists(nmPath),
    detail: nmPath,
  });
  return { ok: checks.every((c) => c.ok), checks };
}

export async function checkPortAvailable(port) {
  const p = Number(port || DEFAULT_PORT);
  return await new Promise((resolve) => {
    const server = net.createServer();
    server.once("error", () => resolve({ port: p, available: false }));
    server.once("listening", () => {
      server.close(() => resolve({ port: p, available: true }));
    });
    try {
      server.listen({ port: p, host: "127.0.0.1", exclusive: true });
    } catch {
      resolve({ port: p, available: false });
    }
  });
}

export async function verifyEnvironment(options = {}) {
  const checks = [];
  const deps = await checkDependencies();
  checks.push(...deps.checks);

  // Data directory writable
  const root = storagePathRoot(options.storagePath);
  let dataOk = false;
  let dataDetail = root;
  try {
    await ensureDir(root);
    const probe = path.join(root, ".dev-write-probe");
    await fs.writeFile(probe, "ok", "utf8");
    await fs.unlink(probe);
    dataOk = true;
  } catch (err) {
    dataDetail = `${root}: ${err.message}`;
  }
  checks.push({ name: "data_writable", ok: dataOk, detail: dataDetail });

  // Port check (soft, informational)
  const port = Number(options.port || process.env.PORT || DEFAULT_PORT);
  const portStatus = await checkPortAvailable(port);
  checks.push({
    name: "port_available",
    ok: portStatus.available,
    detail: String(port),
  });

  // Required env vars (only when BACKEND=openai do we require OPENAI_API_KEY)
  const backend = process.env.BACKEND || "ollama";
  const envRequired = [];
  if (backend === "openai") envRequired.push("OPENAI_API_KEY");
  for (const key of envRequired) {
    checks.push({
      name: `env_${key}`,
      ok: Boolean(process.env[key]),
      detail: process.env[key] ? "set" : "missing",
    });
  }

  return { ok: checks.every((c) => c.ok), checks };
}

// ─── Orchestrator ──────────────────────────────────────────────────────────

export async function runSetup(options = {}) {
  const seed = options.seed || "minimal";
  if (!SEED_TEMPLATES[seed]) {
    throw new Error(`Unknown seed template: ${seed}. Valid: ${Object.keys(SEED_TEMPLATES).join(", ")}`);
  }
  const writeEnv = options.writeEnv !== false;
  const force = Boolean(options.force);
  const storagePath = storagePathRoot(options.storagePath);

  const createdFiles = [];
  const warnings = [];

  // 1. Env file
  let envResult = null;
  if (writeEnv) {
    envResult = await generateEnvFile({
      envPath: options.envPath,
      force,
    });
    if (envResult.written) createdFiles.push(envResult.path);
    else if (envResult.reason === "exists") warnings.push(`.env.local already exists; use force=true to overwrite.`);
  }

  // 2. Data seeding
  await ensureDir(storagePath);
  let seedResult;
  switch (seed) {
    case "demo":
      seedResult = await seedDemo(storagePath);
      break;
    case "testing":
      seedResult = await seedTesting(storagePath);
      break;
    case "full":
      seedResult = await seedFull(storagePath);
      break;
    case "minimal":
    default:
      seedResult = await seedMinimal(storagePath);
      break;
  }
  createdFiles.push(path.join(storagePath, ".dev-seed.json"));

  // 3. Next steps summary
  const nextSteps = [
    "Review .env.local and set any empty values you need (e.g. OPENAI_API_KEY).",
    "Start the server with `npm run dev`.",
    "Open http://localhost:3000 to access the UI.",
  ];

  return {
    success: true,
    seed,
    storagePath,
    createdFiles,
    warnings,
    env: envResult,
    data: seedResult,
    nextSteps,
  };
}

// ─── Reset / status ────────────────────────────────────────────────────────

export async function resetDevEnvironment(options = {}) {
  if (!options.confirm) {
    return { ok: false, error: "Reset requires { confirm: true }." };
  }
  const removed = [];
  const storagePath = storagePathRoot(options.storagePath);
  const envPath = options.envPath ? path.resolve(options.envPath) : path.resolve(process.cwd(), ".env.local");

  if (await exists(storagePath)) {
    try {
      await fs.rm(storagePath, { recursive: true, force: true });
      removed.push(storagePath);
    } catch (err) {
      return { ok: false, error: `Failed to remove ${storagePath}: ${err.message}` };
    }
  }
  if (await exists(envPath)) {
    try {
      await fs.unlink(envPath);
      removed.push(envPath);
    } catch (err) {
      return { ok: false, error: `Failed to remove ${envPath}: ${err.message}` };
    }
  }
  return { ok: true, removed };
}

export async function getDevStatus(options = {}) {
  const storagePath = storagePathRoot(options.storagePath);
  const envPath = options.envPath ? path.resolve(options.envPath) : path.resolve(process.cwd(), ".env.local");

  const envExists = await exists(envPath);
  const storageExists = await exists(storagePath);
  const markerPath = path.join(storagePath, ".dev-seed.json");
  const marker = (await exists(markerPath)) ? await readJsonSafe(markerPath, null) : null;

  // Count users/workspaces/apiKeys from seed files if present
  const usersData = await readJsonSafe(path.join(storagePath, "users.json"), { users: [] });
  const keysData = await readJsonSafe(path.join(storagePath, "api-keys.json"), { keys: [] });

  return {
    envFile: { path: envPath, exists: envExists },
    storage: {
      path: storagePath,
      exists: storageExists,
      seed: marker?.template || null,
      seededAt: marker?.seededAt || null,
    },
    counts: {
      users: Array.isArray(usersData.users) ? usersData.users.length : 0,
      apiKeys: Array.isArray(keysData.keys) ? keysData.keys.length : 0,
    },
    node: process.versions.node,
  };
}

// ─── Synchronous helpers (rare) ───────────────────────────────────────────

export function _syncEnsureDir(p) {
  fsSync.mkdirSync(p, { recursive: true });
}
