{{- if .Values.canary.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "siskelbot.fullname" . }}-canary
  labels:
    {{- include "siskelbot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "siskelbot.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "siskelbot.fullname" . }}-stable
  labels:
    {{- include "siskelbot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "siskelbot.selectorLabels" . | nindent 4 }}
{{- end }}
