{{- if and .Values.metrics.enabled .Values.metrics.synthetic.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: {{ include "siskelbot.fullname" . }}-synthetic
  {{- with .Values.metrics.synthetic.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "siskelbot.labels" . | nindent 4 }}
    {{- with .Values.metrics.synthetic.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  jobName: {{ include "siskelbot.fullname" . }}-synthetic
  prober:
    url: {{ .Values.metrics.synthetic.blackboxExporterUrl | quote }}
    {{- with .Values.metrics.synthetic.proberPath }}
    path: {{ . | quote }}
    {{- end }}
  module: {{ .Values.metrics.synthetic.module | quote }}
  interval: {{ .Values.metrics.synthetic.interval }}
  scrapeTimeout: {{ .Values.metrics.synthetic.scrapeTimeout }}
  targets:
    staticConfig:
      static:
        {{- range .Values.metrics.synthetic.targets }}
        - {{ . | quote }}
        {{- end }}
      {{- with .Values.metrics.synthetic.staticLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
