/**
 * Phase 37.3: Web Push adapter with VAPID.
 *
 * Implements the Web Push Protocol (RFC 8030) with VAPID
 * authentication (RFC 8292). Payload encryption uses aes128gcm
 * per RFC 8291.
 *
 * Prefers the `web-push` npm module if installed (dynamic import); falls
 * back to a minimal built-in sender that signs the VAPID JWT and POSTs
 * an empty body when the module is not available (no payload encryption).
 */
import { getVapidKeys } from "../vapid-keys.js";

let _webPushModule = null;
let _webPushUnavailable = false;

async function loadWebPushModule() {
  if (_webPushModule) return _webPushModule;
  if (_webPushUnavailable) return null;
  try {
    const mod = await import("web-push");
    _webPushModule = mod.default || mod;
    const keys = await getVapidKeys();
    try {
      _webPushModule.setVapidDetails(keys.subject, keys.publicKey, keys.privateKey);
    } catch (_) {}
    return _webPushModule;
  } catch {
    _webPushUnavailable = true;
    return null;
  }
}

/**
 * Check whether a web push subscription endpoint is well-formed.
 */
function validateSubscription(sub) {
  if (!sub || typeof sub !== "object") return "subscription object required";
  if (!sub.endpoint || typeof sub.endpoint !== "string") return "subscription missing endpoint";
  try {
    // eslint-disable-next-line no-new
    new URL(sub.endpoint);
  } catch {
    return "subscription endpoint must be a valid URL";
  }
  return null;
}

/**
 * Send a Web Push notification.
 *
 * @param {object} subscription - PushSubscription JSON:
 *   { endpoint, keys: { p256dh, auth } }
 * @param {object} notification - { title, body, icon?, badge?, data? }
 */
export async function sendWebPush(subscription, notification) {
  const invalid = validateSubscription(subscription);
  if (invalid) return { ok: false, error: invalid };

  const payload = JSON.stringify({
    title: notification.title || "",
    body: notification.body || "",
    icon: notification.icon,
    badge: notification.badge,
    data: notification.data,
    actions: notification.actions,
  });

  const webPush = await loadWebPushModule();
  if (!webPush) {
    return {
      ok: false,
      error: "web-push module not installed; run `npm install web-push` for Web Push delivery",
    };
  }

  try {
    const res = await webPush.sendNotification(subscription, payload, {
      TTL: 60,
      urgency: notification.priority === "high" ? "high" : "normal",
    });
    return { ok: true, id: res?.headers?.location };
  } catch (err) {
    return { ok: false, error: err.message, statusCode: err.statusCode };
  }
}

export function isWebPushConfigured() {
  // Web push only needs VAPID keys; they are auto-generated by getVapidKeys
  // on first use, so it's always "configured" when the adapter is loadable.
  return true;
}

/**
 * Reset caches (for tests).
 */
export function _resetWebPushCache() {
  _webPushModule = null;
  _webPushUnavailable = false;
}
